spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: lucentblock
  jpa:
    show-sql: true
  profiles:
    include: security, mail
  liquibase:
    change-log: classpath:/db/changelog/mysql/DBchangelog-mysql-master.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: choiyt3465@gmail.com
    password: tlhghfjlyjxlqpnv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
