spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: lucentblock
  jpa:
    show-sql: true
  profiles:
    include: security
  liquibase:
    change-log: classpath:/db/changelog/mysql/DBchangelog-mysql-master.xml
    enabled: true