apiVersion: v1
kind: Service
metadata:
  name: lb-api-service
  labels:
    name: lb-api-service
    app: lb-assignment
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: lb-api
    app: lb-assignment
