apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-api-deployment
  labels:
    name: lb-api-deployment
    app: lb-assignment

spec:
  replicas: 2
  selector:
    matchLabels:
      name: lb-api
      app: lb-assignment

  template:
    metadata:
      name: lb-api
      labels:
        app: lb-assignment
        name: lb-api
    spec:
      containers:
        - name: lb-api
          image: rkddlfah02/lb-assignment:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
