apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-mysql-deployment
  labels:
    name: lb-mysql-deployment
    app: lb-assignment

spec:
  replicas: 2
  selector:
    matchLabels:
      name: lb-mysql
      app: lb-assignment
  template:
    metadata:
      name: lb-mysql
      labels:
        name: lb-mysql
        app: lb-assignment
    spec:
      containers:
        - name: lb-mysql
          image: rkddlfah02/mysql:lb_assignment-amd64
          ports:
            - containerPort: 3306
