apiVersion: v1
kind: Service
metadata:
  name: lb-mysql
  labels:
    name: lb-mysql
    app: lb-assignment

spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: lb-mysql
    app: lb-assignment
